Небольшой пулл реквестик в 3 30
klinok066/javaBot pull request #4
Opened 2022-10-30 22:35 UTC by klinok066

ПРошлый пулл реквест лажа ибо я забыл закоммитить, в этом все шикарно

2022-11-05 04:28 UTC, vpyzhyanov commented
Не так я просил ветки называть.

2022-11-05 05:18 UTC, vpyzhyanov requested changes
Не выполнены базовые требования к задаче. Тест тестов и JavaDoc.

В старых тестах перепутаны местами expected и actual
![image](https://user-images.githubusercontent.com/71599019/200102504-30c3ef52-e7dd-428b-bb11-0330125619b9.png)

2022-11-05 05:18 UTC, vpyzhyanov commented on .idea/inspectionProfiles/Project_Default.xml
> +      <option name="METHOD_MATCHER_CONFIG" value="java.util.Formatter,format,java.io.Writer,append,com.google.common.base.Preconditions,checkNotNull,org.hibernate.Session,close,java.io.PrintWriter,pr
Лишние файлы в репозитории

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/Main.java
>          String TELEGRAM_BOT_USERNAME = System.getenv("TELEGRAM_BOT_USERNAME");
Так именуются только константы, не путайте людей

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/connector/Connector.java
>  public interface Connector {
Интерфейс обязан иметь описание и описание всех методов. Он же интерфейс! Он описывает поведение и интерфейс взаимодействия. Привыкайте писать JavaDoc, помогите себе и другим.

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/connector/Connector.java
>      void start();
К чему эти бессмысленные реализации для методов postRequest и getRequest?

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/Main.java
> +        CmdLogic cmd = new CmdLogic("User", "Unknown", "Unknown", -1, requestHandler);
Зачем все эти параметры?

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/Main.java
>          cmd.responseForCDM();
Что такое CDM? И что за ответ от него вы тут просите? В общем метод называет крайне не очевидно.

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/connector/cmdLogic/CmdLogic.java
> +            String messageFromCMD = input.nextLine();
обычно принято какое-то приветственное сообщение писать с описание функций, а не просто ждать ответ. Это очень не очевидно.

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/connector/telegramHandler/TelegramHandler.java
> +                                           update.getMessage().getFrom().getId()
Любите дублирование кода и длинные строчки? А я нет)

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/connector/telegramHandler/TelegramHandler.java
> +                                          );
Скобка уехала, а клоуны остались.

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/connector/telegramHandler/TelegramHandler.java
> +        {
Для кого эти скобки?

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/dataSaver/DataSaver.java
> +final public class DataSaver {
Как обычно отсутствует JavaDoc. А ещё метод говорит, что он занимается сохранением данных, а оказывается ничем таким он не занимается. Тогда вообще не понятно зачем он нужен.

Как только вы в JavaDoc опишете зачем нужен класс, вам будет легче придумать ему правильное название.

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/connector/telegramHandler/TelegramHandler.java
> +public class TelegramHandler extends TelegramLongPollingBot {
Тотальное отсутствие JavaDoc

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +        return db.translateWord(params[0]);
Вот те раз. Кажется этот класс берёт на себя чужие функции

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +    private String toAnswer(String messageString, DataSaver info) { // просто ответ на обычные сообщения
странное название метода

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +    public String onUse(String messageString, DataSaver info) {
Очень странное название метода

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +                params[i - 1] = messageStringWords[i];
С коллекциями работать проще, чем с массивами. Очень рекомендую. Там весь этот цикл можно одной функцией сделать.

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +        return command.substring(1, command.length());
второй аргумент не нужен

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/db/DBHandler.java
> +                return "Привет, добро пожаловать в нашего бота для изучения английского языка!\n"
О_о удивительно, что класс отвечающий за взаимодействие с БД общается с пользователем. Прощай ООП.

2022-11-05 05:18 UTC, vpyzhyanov commented on src/main/java/org/matmech/db/bll/WordsDBSource.java
> +            return "Ошибка! Слово уже существует!\nЕсли хотите что-то поменять в слове, то воспользуйтесь командой /edit";
Аналогично

2022-11-20 19:50 UTC, vpyzhyanov requested changes
На исправление! И на обучение правилам хорошего тона! **В следующий раз если я вижу неисправленные исправления по задаче, сразу буду ставить ноль за задачу!**

2022-11-20 19:50 UTC, vpyzhyanov commented on src/main/java/org/matmech/Main.java
> +//        String access_token = System.getenv("accessToken");
Лишний код

2022-11-20 19:50 UTC, vpyzhyanov commented on src/main/java/org/matmech/connector/Connector.java
>      void start();
Правила хорошего тона предполагают ответы на вопросы и замечания!!!

2022-11-20 19:50 UTC, vpyzhyanov commented on src/main/java/org/matmech/db/DBHandler.java
> + * классов-сервисов и возвращает готовое сообщение пользователю в текстовом виде
> Класс <b>DBHandler</b>

Мы и так видим как называется этот класс. Не надо тут лишней информации.

>  реализует обертку над классами сервисами

Во первых они вообще не сервисы. Во вторых вы пишете детали реализации, но вообще ничего не написали зачем нужен весь этот класс на самом деле.

> возвращает готовое сообщение пользователю в текстовом виде

Что? Серьёзно? Не ну вы наверное просто назвали класс неправильно, наверное его стоит назвать `RequestHandler` или что-то вроде того, но такой уже есть. Неувязочка. В любом случае по описанию, эток класс с БД вообще не должен работать напрямую.

Вы наверняка спросите как описать суть этого класса. Очень просто, нужно посмотреть на его публичные методы и либо перечислить (умеет добавлять пользователя в БД) эти возможности, либо обобщить их и написать одним предложением (сами подумайте каким).

2022-11-20 19:50 UTC, vpyzhyanov commented on src/main/java/org/matmech/db/DBHandler.java
> +        dbConnection = new DBConnection(DB_URL, DB_USERNAME, DB_PASSWORD);
Инетересно получается, а зачем вы эти поля в конструктор передавали, если устанавливать соединения с БД может кто угодно и когда угодно?

2022-11-21 16:21 UTC, iffomko commented on .idea/inspectionProfiles/Project_Default.xml
> +      <option name="METHOD_MATCHER_CONFIG" value="java.util.Formatter,format,java.io.Writer,append,com.google.common.base.Preconditions,checkNotNull,org.hibernate.Session,close,java.io.PrintWriter,pr
Исправлено

2022-11-21 16:22 UTC, iffomko commented on .idea/inspectionProfiles/Project_Default.xml
> +      <option name="METHOD_MATCHER_CONFIG" value="java.util.Formatter,format,java.io.Writer,append,com.google.common.base.Preconditions,checkNotNull,org.hibernate.Session,close,java.io.PrintWriter,pr
Удалил ./idea из ветки + занес эту папку в gitignore

2022-11-21 16:23 UTC, iffomko commented on src/main/java/org/matmech/Main.java
>          String TELEGRAM_BOT_USERNAME = System.getenv("TELEGRAM_BOT_USERNAME");
Исправил, сделал их константами, так как их значения достаются и соответствующих переменных окружения один раз при старте программы

2022-11-21 16:26 UTC, iffomko commented on src/main/java/org/matmech/connector/Connector.java
>  public interface Connector {
Исправлено, написан javadoc для метода и интерфейса

2022-11-21 16:28 UTC, iffomko commented on src/main/java/org/matmech/connector/Connector.java
>      void start();
Удалил эти методы за их не надобностью. Изначально предполагалось, что работа с POST и GET запросами будет вынесена в эти методы, но позже планы сильно поменялись

2022-11-21 16:42 UTC, iffomko commented on src/main/java/org/matmech/Main.java
> +        CmdLogic cmd = new CmdLogic("User", "Unknown", "Unknown", -1, requestHandler);
Исправил, добавил нормальную авторизацию через консоль

2022-11-21 16:46 UTC, iffomko commented on src/main/java/org/matmech/Main.java
>          cmd.responseForCDM();
Исправил, вынес запуск бота в метод старт, и исправил название метода responseForCDM на более подходящее - startChat

2022-11-21 16:48 UTC, iffomko commented on src/main/java/org/matmech/connector/cmdLogic/CmdLogic.java
> +            String messageFromCMD = input.nextLine();
Добавил приветственное сообщение

2022-11-21 16:52 UTC, iffomko commented on src/main/java/org/matmech/connector/telegramHandler/TelegramHandler.java
> +                                           update.getMessage().getFrom().getId()
Исправил

2022-11-21 16:52 UTC, iffomko commented on src/main/java/org/matmech/connector/telegramHandler/TelegramHandler.java
> +                                          );
Исправил

2022-11-21 16:53 UTC, iffomko commented on src/main/java/org/matmech/connector/telegramHandler/TelegramHandler.java
> +        {
Убрал скобки)

2022-11-21 16:58 UTC, iffomko commented on src/main/java/org/matmech/dataSaver/DataSaver.java
> +final public class DataSaver {
Написал JavaDoc и исправил название на более подходящее

2022-11-21 17:00 UTC, iffomko commented on src/main/java/org/matmech/connector/telegramHandler/TelegramHandler.java
> +public class TelegramHandler extends TelegramLongPollingBot {
Исправленно

2022-11-21 17:03 UTC, iffomko commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +        return db.translateWord(params[0]);
Мне хотелось задать одинаковую сигнатуру для всех методов, инкапсулировав логику передачи передачи параметров в функции, которые работают с бд

2022-11-21 17:03 UTC, iffomko commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +        return db.translateWord(params[0]);
Как по другому сделать - я не знаю

2022-11-21 17:04 UTC, iffomko commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +        return db.translateWord(params[0]);
Просто передавать в эти функции параметры, мне кажется, не надо. Хочется это инкапсулировать

2022-11-21 17:07 UTC, iffomko commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +    private String toAnswer(String messageString, DataSaver info) { // просто ответ на обычные сообщения
Исправил название

2022-11-21 17:07 UTC, iffomko commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +    public String onUse(String messageString, DataSaver info) {
Исправил название

2022-11-21 17:08 UTC, iffomko commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +                params[i - 1] = messageStringWords[i];
Исправил все на коллекции

2022-11-21 17:08 UTC, iffomko commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +        return command.substring(1, command.length());
Убрал

2022-11-21 17:10 UTC, iffomko commented on src/main/java/org/matmech/db/bll/WordsDBSource.java
> +            return "Ошибка! Слово уже существует!\nЕсли хотите что-то поменять в слове, то воспользуйтесь командой /edit";
В классах сервисах - исправил

2022-11-21 17:14 UTC, iffomko commented on src/main/java/org/matmech/db/DBHandler.java
> +                return "Привет, добро пожаловать в нашего бота для изучения английского языка!\n"
Исправил в классах-сервисах возврат сообщения для пользователя, но не очевидно почему нужно исправить это для класса DBHandler, который является оберткой для этих классов-сервисов, которые обслуживают одну из таблиц в БД?

Почему нельзя сделать возврат сообщения для пользователя, которые будет фиксированное?

Или стоит сделать возврат значения какого-то, а потом уже сам requestHandler сам определит какое сообщение возвращать? Или лучше написать класс, который будет возвращать сообщения для пользователей, а requestHandler будет его дергать, вместо базы данных?

2022-11-21 17:26 UTC, iffomko commented on src/main/java/org/matmech/db/DBHandler.java
> +        dbConnection = new DBConnection(DB_URL, DB_USERNAME, DB_PASSWORD);
Понял, исправил, и в правду ломало логику работы приложения

2022-11-21 17:27 UTC, iffomko commented on src/main/java/org/matmech/db/DBHandler.java
> + * классов-сервисов и возвращает готовое сообщение пользователю в текстовом виде
Вроде исправил, но не знаю правильно или нет

2022-11-21 17:27 UTC, iffomko commented on src/main/java/org/matmech/Main.java
> +//        String access_token = System.getenv("accessToken");
Убрал

2022-11-26 16:56 UTC, vpyzhyanov commented on src/main/java/org/matmech/Main.java
>          String TELEGRAM_BOT_USERNAME = System.getenv("TELEGRAM_BOT_USERNAME");
Уж не знаю в каком вы месте их сделали константами, но точно не тут. Тут по сути ничего не изменилось. Давайте синхронизируем понимание, что вы считаете константой?

В общепринятом понимании константа - это **поле класса**, которое помечено как static final.

2022-11-26 17:06 UTC, vpyzhyanov commented on src/main/java/org/matmech/connector/telegramHandler/TelegramHandler.java
> +                                          );
эта грустная подмигивающая скобка по прежнему уехала. Ну да ладно.

2022-11-26 18:02 UTC, vpyzhyanov requested changes
Как поправите (что получится), можете мёрдижть. Задачу я зачёл. Дальше поговорим в следующей задаче.

2022-11-26 18:02 UTC, vpyzhyanov commented on src/main/java/org/matmech/connector/telegramHandler/TelegramHandler.java
> +            User userData = update.getMessage().getFrom();
Нужно переименовать переменную. Тип говорит о том, что это пользователь, а не данные пользователя. Несоответствие. Любое такое несоответствие путает разработчика.

2022-11-26 18:02 UTC, vpyzhyanov commented on src/main/java/org/matmech/connector/telegramHandler/TelegramHandler.java
> +            UserData data = new UserData(
Тип говорит, что это данные пользователя, но на самом деле это информация о пользователе. Тут несколько моментов:

1. имя переменной неправильное
2. Зачем вообще нужен UserData, если есть User? Он и так содержит те поля, которые вы копируете.
3. Слово data используется только для обозначения данных. Данные в нашем контексте - это сообщения пользователя и ответы на них, а ещё всякие ресурсы вроде картинок.

2022-11-26 18:02 UTC, vpyzhyanov commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +public class RequestHandler {
Не выполнены базовые требования по наличию JavaDoc. Неужели так сложно?

2022-11-26 18:02 UTC, vpyzhyanov commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +        return db.translateWord(params[0]);
> Мне хотелось задать одинаковую сигнатуру для всех методов, инкапсулировав логику передачи передачи параметров в функции, которые работают с бд

Ничего не понял. Какие параметры? Какая инкапсуляция? К параметрам вопросов нет. Одинаковую сигнатуру? Зачем? А по поводу инкапсуляции кажется, что вы пытаетесь спрятать куда-то не туда.

В чём тут на самом деле проблема: класс, который берёт на себя чужие функции - это DBHandler. Правильная архитектура такова, что DBHandler взаимодействует с базой и больше ничего не делает. А уже RequestHandler занимается формирование сообщений пользователю и всякой логикой взаимодейтсвия с пользователем.

2022-11-26 18:02 UTC, vpyzhyanov commented on src/main/java/org/matmech/requestHandler/RequestHandler.java
> +            params.remove(0);
Похоже вы прогуляли тему коллекций. Какова сложность этой операции?

А ещё тут вы тратите в 2 раза больше памяти чем нужно. Подсказать как сделать или сами попробуете догадаться?

Подсказка: со строками можно работать аналогично.

2022-11-26 18:02 UTC, vpyzhyanov commented on src/main/java/org/matmech/db/DBHandler.java
> +                return "Привет, добро пожаловать в нашего бота для изучения английского языка!\n"
Теперь я наконец-то понял вашу задумку. Не могу вам ничего ответить пока вы не напишете JavaDoc для requestHandler и не объясните себе и мне зачем он нужен.

А DBHandler имеет название, которое не совпадает с него описанием. Название говорит, что он занимается обработкой базы данных. Что это такое приходится фантазировать, но я полагаю что имеется в виду класс для доступа к данным, хранящимся в БД.

Судя по всему выбрана очень неудачная архитектура. Кажется тут названия и описания нас не спасут.

2022-11-26 18:02 UTC, vpyzhyanov commented on src/main/java/org/matmech/db/bll/DBSource.java
> +abstract public class DBSource {
Название и описание не соответствуют друг другу

2022-11-26 18:02 UTC, vpyzhyanov commented on src/main/java/org/matmech/db/bll/DBSource.java
> +    protected HashMap<String, String> createParams(String type, String value) {
Вам правда необходим именно HashMap?

2022-11-26 18:02 UTC, vpyzhyanov commented on src/main/java/org/matmech/db/bll/WordsDBSource.java
> +            return "Ошибка! Слово уже существует!\nЕсли хотите что-то поменять в слове, то воспользуйтесь командой /edit";
Каких классах сервисах? Это не сервис! Вы же сами написали, что это источник данных (слов), который берёт данные из БД. При чём тут сервис?!

2022-11-26 18:02 UTC, vpyzhyanov commented on src/main/java/org/matmech/db/DBHandler.java
> + * классов-сервисов и возвращает готовое сообщение пользователю в текстовом виде
Стало лучше! Остался лишь вопрос самого существования этого класса, но это мы в других местах уже обсуждаем.

2022-11-26 19:08 UTC, vpyzhyanov requested changes
В общем, по тестам: тесты отсутствуют. У вас есть тесты на классы "псевдосервисы", которые просто занимаются взаимодействием с БД. Но нет ни одного теста на настоящие сервисы. От этого тестирования крайне мало пользы, т.к. вы проверили только слой, который взаимодействует с БД. Но никак не протестировали слой логики. А это очень плохо. Важно было протестировать классы, которые отвечают за логику и взаимодействие с пользователем, это RequestHandler и DBHandler, один из которых непонятно зачем вообще существует.

2022-11-26 19:08 UTC, vpyzhyanov commented on src/test/java/TestCommands/TestRequestHandler.java
>  public class TestRequestHandler extends TestCase {
Что то я поторопился. Без тестов задачу не могу принять. А тестов на RequestHandler вообще нет. А то что тут есть ничего реально полезного не тестирует.

2022-11-26 19:08 UTC, vpyzhyanov commented on src/test/java/testServiceClasses/TestDictonaryDBSource.java
> +        assertTrue(dictonaryDBSource.createDictonary(dictonary, dbConnection));
Тут вы тестируете лишь малую часть этого метода. Проверку на пользователя. А можно тут ещё протестировать с какими параметрами вызовется команда создания в dbConnection.

2022-11-26 19:08 UTC, vpyzhyanov commented on src/test/java/testServiceClasses/TestDictonaryDBSource.java
> +            ArrayList<HashMap<String, String>> response = new ArrayList<HashMap<String, String>>();
Где интерфейсы?

2022-11-26 19:08 UTC, vpyzhyanov commented on src/test/java/testServiceClasses/TestDictonaryDBSource.java
> +            HashMap<String, String> dictonaryResponse = new HashMap<String, String>();
Где интерфейсы?

2022-11-26 19:08 UTC, vpyzhyanov commented on src/test/java/testServiceClasses/TestDictonaryDBSource.java
> +            Dictonary dictonary = new Dictonary();
Опечатка. Dict**i**onary

2022-11-26 19:08 UTC, vpyzhyanov commented on src/test/java/testServiceClasses/TestDictonaryDBSource.java
> +            throw new RuntimeException(e);
Зачем? Просто в методе описать throws SQLException

2022-11-26 19:08 UTC, vpyzhyanov commented on src/test/java/testServiceClasses/TestDictonaryDBSource.java
> +     * Unit-тест метода getDictonaryId: проверяет его неправильную работу
> проверяет его неправильную работу

Аха ха, очень смешно)

2022-11-26 19:08 UTC, vpyzhyanov commented on src/test/java/testServiceClasses/TestDictonaryDBSource.java
> +            ArrayList<HashMap<String, String>> response = new ArrayList<HashMap<String, String>>();
Я учил использовать интерфейсы

2022-11-26 19:08 UTC, vpyzhyanov commented on src/test/java/testServiceClasses/TestDictonaryDBSource.java
> +            assertEquals(10, dictonaryDBSource.getDictonaryId(dictonary, dbConnection));
Стоп! Что? Вы идёте в базу за идентификатором имея сам объект? А нельзя не лезть в базу а просто вызывать у него getID()? Хотя я привык работать с объектами, а тут наверное всё иначе...

И действительно, тут всё иначе. Оказывается вы хотите получить словарь зная пользователя, кому он принадлежит. Никогда бы не догадался не изучив сам метод и все места, где он используется. В общем тут надо разбираться:

1. Зачем передавать dbConnection, его надо в конструктор
2. `dictonaryDBSource.getDictonaryId(user);` - так гораздо понятнее, разве нет?!
3. Зачем вам целый класс Dictonary ради одного поля userId? Это всё равно, что целый факультет создавать для одного студента.

2022-11-26 19:08 UTC, vpyzhyanov commented on src/main/java/org/matmech/db/models/Users.java
> +public class Users extends BaseModel{
Откуда множественное число? Притом во всех классах этого пакета.

И JavaDoc

2022-11-26 19:08 UTC, vpyzhyanov commented on src/test/java/testServiceClasses/TestUsersDBSource.java
> +            System.out.println("Тестирование провалено!\n" + e.getMessage());
Это шутка такая? Я очень надеюсь вы осознаёте почему я считаю это шуткой?

2022-11-26 19:08 UTC, vpyzhyanov commented on src/test/java/testServiceClasses/TestUsersDBSource.java
> +            ArrayList<HashMap<String, String>> response = new ArrayList<HashMap<String, String>>();
Интерфейсы

2022-12-11 10:02 UTC, merged