Таск 3
klinok066/javaBot pull request #6
Opened 2022-12-14 16:54 UTC by iffomko

2022-12-16 06:42 UTC, vpyzhyanov requested changes
Необходимо сделать rebase от master.
И исправить замечания.

2022-12-16 06:42 UTC, vpyzhyanov commented on src/main/java/org/matmech/context/contextHandler/handlers/wordAdd/WordAddCommand.java
> +            Map<String, String> params = context.getParams(CHAT_ID);
Дублирование
![image](https://user-images.githubusercontent.com/71599019/208034252-4689e433-d8a9-4f4f-bf79-f6e83e412a78.png)

2022-12-16 06:42 UTC, vpyzhyanov commented on src/main/java/org/matmech/context/contextHandler/handlers/wordAdd/WordAddCommand.java
> +            return List.of(db.wordAdd(params.get("word"), params.get("translate"),params.get("group"),TAG));
отсутствует форматирование кода. Код без пробелов - это для сильных глазом)

2022-12-16 06:42 UTC, vpyzhyanov commented on src/main/java/org/matmech/context/contextHandler/handlers/testCommand/TestCommand.java
> +        String currentQuestion = String.valueOf(Integer.parseInt(params.get("currentQuestion")) + 1);
жесть! Кто вас заставлял хранить всё в строках? Можно же класс создать.

2022-12-16 06:42 UTC, vpyzhyanov commented on src/main/java/org/matmech/context/Context.java
> +    private HashMap<String, String> searchItem(long chatId) {
тут должен быть интерфейс

2022-12-16 06:42 UTC, vpyzhyanov commented on src/main/java/org/matmech/context/Context.java
> +        cache = new ArrayList<HashMap<String, String>>();
тут должен быть интерфейс Map

2022-12-16 06:42 UTC, vpyzhyanov commented on src/main/java/org/matmech/context/Context.java
> +    public boolean addParams(long chatId, String processName, String itemName, String itemValue) {
Почему множественное число? Один же параметр добавляет

2022-12-16 06:42 UTC, vpyzhyanov commented on src/main/java/org/matmech/context/Context.java
> +    DBConnection dbConnection;
Вы сами-то просматриваете свой код? Почему тут неиспользуемые поля?

2022-12-16 06:42 UTC, vpyzhyanov commented on src/main/java/org/matmech/context/Context.java
> +public class Context { // написать метод createContext(long chatId), и зарефакторить везде код под то, что он ничего не делает, если контекста нет для чата
Этот комментарий должен быть в отдельной строке и помечен как `//TODO`

2022-12-16 06:42 UTC, vpyzhyanov commented on src/main/java/org/matmech/params/Params.java
> +        if (WORD == null){
Очень жёстко код завязан на последовательность. Судя по всему этот код очень жёстко и при этом абсолютно неявно связан с каким-то другим кодом (даже не представляю с каким), в котором у пользователя запрашиваются эти параметры. То есть нет связи вопроса и параметра, просто надеемся на правильную последовательность **в двух разных местах**.

2022-12-16 06:42 UTC, vpyzhyanov commented on src/main/java/org/matmech/params/Params.java
> +     * 1. В методе setParams написать новый кейс и соответствующий метод
Если есть возможность что-то забыть, это обязательно будет забыто. Как раз это относится к методу `setParams`

2022-12-16 06:42 UTC, vpyzhyanov commented on src/main/java/org/matmech/params/Params.java
> +        if (WORD == null){
Забавно, но я так и не смог найти код, где у пользователя запрашиваются эти параметры=(. Цепочка вызовов нереально огромная, целый лабиринт. Если вы хотели этот код спрятать, то у вас получилось!

2022-12-16 06:42 UTC, vpyzhyanov commented on src/test/java/TestCommands/TestRequestHandler.java
> +    private RequestHandler handler = new RequestHandler(db, context);
![image](https://user-images.githubusercontent.com/71599019/208037337-7cd8b560-a83b-40d9-9701-a9ffea934b2f.png)

2022-12-16 06:42 UTC, vpyzhyanov commented on src/main/java/org/matmech/db/bll/DictonaryDBSource.java
> +    public int getDictonaryId(Dictionary dictionary) throws SQLException {
Насколько я вижу замечание из предыдущего Pull Reqiest до сих пор не исправлено. Очень плохо, очень очень плохо!

2022-12-16 06:42 UTC, vpyzhyanov commented on src/test/java/TestCommands/TestRequestHandler.java
> +    public void testGetGroupForTesting() {
Тесты не компилируются, не могу из проверить. Значит замечание: нет тестов.

2022-12-17 15:54 UTC, iffomko commented on src/main/java/org/matmech/params/Params.java
> +        if (WORD == null){
понял, полностью согласен, исправил

2022-12-17 15:56 UTC, iffomko commented on src/main/java/org/matmech/context/Context.java
> +        cache = new ArrayList<HashMap<String, String>>();
исправил

2022-12-17 15:56 UTC, iffomko commented on src/main/java/org/matmech/context/Context.java
> +    DBConnection dbConnection;
Исправил

2022-12-17 15:57 UTC, iffomko commented on src/main/java/org/matmech/context/Context.java
> +public class Context { // написать метод createContext(long chatId), и зарефакторить везде код под то, что он ничего не делает, если контекста нет для чата
Исправил

2022-12-17 15:57 UTC, iffomko commented on src/main/java/org/matmech/params/Params.java
> +     * 1. В методе setParams написать новый кейс и соответствующий метод
Исправил

2022-12-17 15:58 UTC, iffomko commented on src/main/java/org/matmech/context/Context.java
> +    private HashMap<String, String> searchItem(long chatId) {
Исправил

2022-12-17 16:00 UTC, iffomko commented on src/main/java/org/matmech/context/contextHandler/handlers/testCommand/TestCommand.java
> +        String currentQuestion = String.valueOf(Integer.parseInt(params.get("currentQuestion")) + 1);
Не много не понимаю, что вы имете ввиду
Просто там могут возвращаться различные данные из бд (числа, даты, строки)
И так как тема "управление владением" будет только в следующем семестре, я не не могу передавать объект (Ленивый итератор, или как там его, не помню), в возвращаемом значении, так как он должен быть обязательно закрыт
Поэтому принял решение сделать все строках

2022-12-19 02:53 UTC, iffomko commented on src/main/java/org/matmech/context/contextHandler/handlers/wordAdd/WordAddCommand.java
> +            return List.of(db.wordAdd(params.get("word"), params.get("translate"),params.get("group"),TAG));
исправленно

2022-12-19 02:56 UTC, iffomko commented on src/main/java/org/matmech/db/bll/DictonaryDBSource.java
> +    public int getDictonaryId(Dictionary dictionary) throws SQLException {
Видимо упустил этот момент, исправил!

2022-12-19 02:56 UTC, iffomko commented on src/test/java/TestCommands/TestRequestHandler.java
> +    public void testGetGroupForTesting() {
Теперь должно все компилироваться

2022-12-19 02:56 UTC, iffomko commented on src/main/java/org/matmech/context/Context.java
> +    public boolean addParams(long chatId, String processName, String itemName, String itemValue) {
Исправил

2022-12-19 03:04 UTC, iffomko commented on src/main/java/org/matmech/context/contextHandler/handlers/wordAdd/WordAddCommand.java
> +            Map<String, String> params = context.getParams(CHAT_ID);
исправил

2022-12-20 05:45 UTC, vpyzhyanov commented on src/main/java/org/matmech/context/contextHandler/handlers/testCommand/TestCommand.java
> +        String currentQuestion = String.valueOf(Integer.parseInt(params.get("currentQuestion")) + 1);
При чём тут итератор? У вас же параметры для каждой команды заранее известны. Это значит, что заранее известны все типы. Если создать класс параметров под каждую команду, то этих лишних преобразований не будет.

2022-12-20 05:46 UTC, vpyzhyanov commented
задачу принял

2022-12-22 08:15 UTC, merged